/* load.sql
* sql script file created by Xiongfeng Hu
*/ 


LOAD DATA LOCAL INFILE '../data/movie.csv' INTO TABLE Movie
FIELDS TERMINATED BY ','OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE '../data/actor1.csv' INTO TABLE Actor
FIELDS TERMINATED BY ','OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE '../data/actor2.csv' INTO TABLE Actor
FIELDS TERMINATED BY ','OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE '../data/actor3.csv' INTO TABLE Actor
FIELDS TERMINATED BY ','OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE '../data/director.csv' INTO TABLE Director
FIELDS TERMINATED BY ','OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE '../data/moviedirector.csv' INTO TABLE MovieDirector
FIELDS TERMINATED BY ','OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE '../data/moviegenre.csv' INTO TABLE MovieGenre
FIELDS TERMINATED BY ','OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE '../data/movieactor1.csv' INTO TABLE MovieActor
FIELDS TERMINATED BY ','OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE '../data/movieactor2.csv' INTO TABLE MovieActor
FIELDS TERMINATED BY ','OPTIONALLY ENCLOSED BY '"';

INSERT INTO MaxPersonID VALUES(69000);

INSERT INTO MaxMovieID VALUES(4750);
